[package]
name = "vmm-providers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
dirs = "6.0.0"
lib-vmm = "0.2.0"
reqwest = { version = "0.12.24", features=["json"]}
serde = "1.0.228"
serde_json = "1.0.145"
steamlocate = "2.0.1"
